name: Gold Tracker Bot

on:
  schedule:
    - cron: '0 * * * *' # Toutes les heures
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: pip install yfinance

      - name: Exécuter le script
        # On précise le chemin vers le dossier .github/scripts/
        run: python .github/scripts/gold_update.py

      - name: Commit et Push
        run: |
          git config --global user.name "Gold-Bot"
          git config --global user.email "bot@github.com"
          git add JustTEST/bot_test/logger.txt
          # On vérifie s'il y a des changements avant de commit pour éviter les erreurs
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Gold Price: $(date)" && git push)
